// Portfolio Data
// This file is auto-generated by the Admin Panel
// To update: Login to admin.html → Create/edit items → Click "Download for Publishing"
// Then replace this file with the downloaded one and commit to Git

const portfolioData = [
    // Your portfolio items will appear here after publishing from admin panel
];

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = portfolioData;
}
